version: '3'

services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: "dbapp"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - db_network
  web:
    restart: always
    build: .
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn --timeout=30 --workers=2 --bind 0.0.0.0:8000 dj.wsgi:application" #python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static-volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  nginx:
    image: nginx:latest
    ports:
      - "3000:8000"
    volumes:
      - static-volume:/app/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
  db-volume:
